/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GradientNewRouteImport } from './routes/gradient/new'
import { Route as GradientIdRouteImport } from './routes/gradient/$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientNewRoute = GradientNewRouteImport.update({
  id: '/gradient/new',
  path: '/gradient/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientIdRoute = GradientIdRouteImport.update({
  id: '/gradient/$id',
  path: '/gradient/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gradient/$id': typeof GradientIdRoute
  '/gradient/new': typeof GradientNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gradient/$id': typeof GradientIdRoute
  '/gradient/new': typeof GradientNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gradient/$id': typeof GradientIdRoute
  '/gradient/new': typeof GradientNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/gradient/$id' | '/gradient/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/gradient/$id' | '/gradient/new'
  id: '__root__' | '/' | '/about' | '/gradient/$id' | '/gradient/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GradientIdRoute: typeof GradientIdRoute
  GradientNewRoute: typeof GradientNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradient/new': {
      id: '/gradient/new'
      path: '/gradient/new'
      fullPath: '/gradient/new'
      preLoaderRoute: typeof GradientNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradient/$id': {
      id: '/gradient/$id'
      path: '/gradient/$id'
      fullPath: '/gradient/$id'
      preLoaderRoute: typeof GradientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GradientIdRoute: GradientIdRoute,
  GradientNewRoute: GradientNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
